main: com.thizthizzydizzy.treefeller.TreeFeller
version: 1.25.1
api-version: 1.16
folia-supported: true
author: ThizThizzyDizzy
website: "https://www.spigotmc.org/resources/thizzyz-tree-feller.64346/"
name: TreeFeller
commands:
    treefeller:
        description: TreeFeller commands
        usage: /treefeller (help|toggle [on|off]|on|off|reload|debug [on|off]|config)
softdepend:
  - mcMMO
  - Lands
  