main: com.thizthizzydizzy.treefeller.TreeFeller
version: 1.26.2
api-version: "1.21.5"
folia-supported: true
author: ThizThizzyDizzy
website: "https://www.spigotmc.org/resources/thizzyz-tree-feller.64346/"
name: TreeFeller-Folia
commands:
    treefeller:
        description: TreeFeller commands
        usage: /treefeller (help|toggle [on|off]|on|off|reload|debug [on|off]|config)
softdepend:
  - mcMMO
  - Lands
  - CoreProtect
  - Drop2Inventory